name: Variable sharing between jobs

on: [pull_request]

jobs:
  job1: 
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    needs: job1
    if: ${{needs.job1.outputs.output1 }}
    runs-on: ubuntu-latest
    steps:
      - name: use job1 outputs
        run: echo ${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }}
